version: "2"
services:
  SwissTopoTiles:
    image: klokantech/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    command: merged.mbtiles
  web:
    image: nhofer/tile-demo
    build: .
    command: python3 -m http.server
    ports: 
      - "8000:8000"
