version: "2"
services:
  SwitzerlandMobilityTiles:
    image: klokantech/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    command: CHMobility_poi_web_swiss.mbtiles
  web:
    image: nhofer/tile-demo-dev
    build: .
    command: npm run-script docker
    ports: 
      - "8000:8000"
